### ISSUE TITLE
Publishing failing

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s-session#142]
Publishing is failing because it's still using oss.sonatype.org instead of s01.oss.sonatype.org.  Moving to sbt-http4s-org would fix it.

**Comment by armanbilge** [comment]
Now it's failing with this.
```
[error] Not a valid command: tlCiRelease (similar: tlRelease, tlReleaseLocal, sonatypeRelease)
[error] Not a valid project ID: tlCiRelease
[error] Expected ':'
[error] Not a valid key: tlCiRelease (similar: tlCiReleaseTags, tlJdkRelease, tlCiReleaseBranches)
[error] tlCiRelease
```

Not sure why ... the plugin shouldn't generate actions with unsupported commands, that would be really weird.

**Comment by danicheg** [comment]
Can it be smth with the settings of the repo?

**Comment by armanbilge** [comment]
Oh, I figured it out!

**Comment by armanbilge** [comment]
(Snapshot) publishing appears to be fixed. But it looks like there are old secrets on this repo which are overriding the org secrets, that may cause a problem for proper release.

**Comment by rossabaker** [comment]
I purged the repo secrets.

**Comment by danicheg** [comment]
It's alive! https://search.maven.org/artifact/org.http4s/http4s-session_2.13/0.1.0/jar
