### ISSUE TITLE
Usage with Scala 3.3.0

### ISSUE THREAD

**Issue by KaranAhlawat** [http4s/http4s-session#189]
The `build.sbt` shows we should be able to use the library with Scala 3.3.0, but adding it as a dependency in mill as shown below fails, since it looks like there wasn't a release with the 3.3.0 build. 

```
ivy"org.http4s::http4s-session:<version>"
```

Looks like a new release is all that's needed, but not sure. Any help is appreciated.

**Comment by danicheg** [comment]
Hey! We haven't published this library for 4 months, so that's why Scala 3 support isn't available yet. I will draft the release as soon as possible. Stay tuned!

**Comment by danicheg** [comment]
https://github.com/http4s/http4s-session/releases/tag/v0.2.0
Artefacts ought to appear in Maven Central in 4-8 hours (on average).

**Comment by KaranAhlawat** [comment]
Alright, should I close this or after it appears on Maven?
