### ISSUE TITLE
Bikeshed Package Name

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s-session#3]
This was `io.chrisdavenport.http4ssession` which was verbose but unique. What do we want this to be called?

**Comment by rossabaker** [comment]
`org.http4s.session` seems pretty obvious to me?

**Comment by ChristopherDavenport** [comment]
Thats definitely fine. As long as we're ok with such a prominent package

**Comment by rossabaker** [comment]
It fits the pattern of the other modules.  Grab it!
