### ISSUE TITLE
Is microsite published?

### ISSUE THREAD

**Issue by danicheg** [http4s/http4s-session#34]
https://http4s.github.io/http4s-session --> 404

**Comment by ChristopherDavenport** [comment]
I think we need @rossabaker  to setup something in Netlify to do this. since we delegate this stuff to them. Or maybe I am wrong.  This was publishing when it was in davenverse.

**Comment by rossabaker** [comment]
I added a CNAME for session.http4s.org to http4s.github.io.  It's not letting me enable https, but allegedly that takes 24 hours.  We moved to Netlify back when GitHub Pages wouldn't do certs on custom domains, and I really don't know how it works in modern times.

**Comment by danicheg** [comment]
@rossabaker thanks!

**Comment by rossabaker** [comment]
I just set up the alias in GitHub and it let me enforce SSL.
